###############
# BUILD IMAGE #
###############
FROM frolvlad/alpine-miniconda3:python3.7 AS build

# set working directory
WORKDIR /usr/src/app

# install packages
# clean
COPY ./docker/environment.yml .
RUN conda update -n base conda && \
          conda env update && \
          find /opt/conda/ -follow -type f -name '*.a' -delete && \
          find /opt/conda/ -follow -type f -name '*.pyc' -delete && \
          find /opt/conda/ -follow -type f -name '*.js.map' -delete

#################
# RUNTIME IMAGE #
#################
FROM frolvlad/alpine-miniconda3:python3.7 AS runtime

# copy from build image
RUN rm -rf /opt/conda
COPY --from=build /opt/conda /opt/conda

# set working directory
WORKDIR /usr/src/app

# add non-root user and give permissions
RUN addgroup --system user && adduser --system -G user user
RUN chown -R user:user /usr/src/app && \
      chmod -R 755 /usr/src/app
USER user

# copy code
COPY ./code /code
COPY ./notebooks /notebooks

# environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
