###############
# BUILD IMAGE #
###############
FROM frolvlad/alpine-miniconda3:python3.7 AS build

# set working directory
WORKDIR /usr/src/app

# install packages
# clean
COPY ./docker/environment-prod.yml .
RUN conda update -n base conda && \
          conda env create -f environment-prod.yml && \
          conda clean -afy && \
          find /opt/conda/ -follow -type f -name '*.a' -delete && \
          find /opt/conda/ -follow -type f -name '*.pyc' -delete && \
          find /opt/conda/ -follow -type f -name '*.js.map' -delete

#################
# RUNTIME IMAGE #
#################
FROM frolvlad/alpine-miniconda3:python3.7 AS runtime

# create user
ARG USER_ID
ARG GROUP_ID

# add non-root user and give permissions to workdir
RUN addgroup --gid $GROUP_ID user && \
          adduser --system --gecos '' -D -u $USER_ID -g $GROUP_ID user && \
          mkdir -p /usr/src/app && \
          chown -R user:user /usr/src/app

# copy from build image
RUN rm -rf /opt/conda
COPY --chown=user:user --from=build /opt/conda /opt/conda

# set working directory
WORKDIR /usr/src/app

# switch to non-root user
USER user

# copy code
COPY ./code /code
COPY ./notebooks /notebooks

# environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# run conda commands from environment
ENTRYPOINT ["conda", "run", "-n", "ds-ml"]
